using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Coursework.Models
{
    public class Product
    {
        //prime key, values generated by db
        public int ID { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
        //relationship with Sale
        public int sale_id { get; set; }
        //navigation property (dropdown in the app)
        public virtual Sale Sale { get; set; }
    }
}